### ISSUE TITLE
Site Documentation

### ISSUE THREAD

**Issue by selgerosa** [selinagerosa/ramakrishna_vivekananda#13]
Take screenshots of old website pages.
- Home page
- Books pages
-

~20 + pics so I can pick later

**Comment by C-Lion** [comment]
What is the URL of these 20 pages?

**Comment by selgerosa** [comment]
Hi! Here is the list, thanks for reaching out!

top level pages
http://www.ramakrishna.org/index.htm
http://www.ramakrishna.org/act_srv.htm
http://www.ramakrishna.org/activities/events/memorable.htm
http://www.ramakrishna.org/sy.htm
http://www.ramakrishna.org/sun_srv.htm
http://www.ramakrishna.org/activities/events/MEvents8.htm
http://www.ramakrishna.org/cntrlist.htm
teachings
http://www.ramakrishna.org/rmk.htm
http://www.ramakrishna.org/ut_hm.htm
http://www.ramakrishna.org/sv_great.htm
http://www.ramakrishna.org/chcgfull.htm
http://www.ramakrishna.org/activities/message/message25.htm
http://www.ramakrishna.org/activities/events/MEvents6.htm
shop
http://www.ramakrishna.org/catalog/books.htm
http://www.ramakrishna.org/catalog/archive/sv_abiography.htm
http://www.ramakrishna.org/catalog/bk_sa_publ.htm
http://www.ramakrishna.org/catalog/bk_sn_publ.htm
http://www.ramakrishna.org/catalog/videos.htm
http://www.ramakrishna.org/catalog/search.htm
http://www.ramakrishna.org/catalog/bk_of_month.htm
http://www.ramakrishna.org/catalog/photos.htm
http://www.ramakrishna.org/catalog/ordrform.htm
http://www.ramakrishna.org/catalog/archive/Spirit_of_Hinduism.htm

Ultimately, I'd like to put the whole site on the internet archive before the relaunch goes live; I think it is a great example of web design in the 90s. But these are specifically for project documentation.
